name: CHECKING API POI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  testing-api:
    runs-on: ubuntu-latest

    steps:
    - name: Make Request
      id: myRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: "https://openhacktch9q931poi.azurewebsites.net/api/healthcheck/poi"
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
  
