name: Deploy POI API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  DOTNET_VERSION: '3.1'           # set this to the dot net version to use

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and test
        run: |
          cd apis/poi/tests/IntegrationTests
          dotnet restore
          dotnet build .
          dotnet test .
    
      - name: Creating issue
        if: ${{ failure() }}
        - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-issue
        - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
        - run: 'echo Created ${{ steps.create-issue.outputs.url }}'