name: Deploy POI API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  DOTNET_VERSION: '3.1'           # set this to the dot net version to use

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and test
        run: |
          cd apis/poi
          dotnet restore
          dotnet build .
          dotnet test .