name: CI API POI

on:
  push:
    branches:
      - main
    paths: 
      - apis/poi/**
  pull_request:
    branches:
      - '*'

env:
  DOTNET_VERSION: '3.1'           # set this to the dot net version to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repo
      - uses: actions/checkout@master
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and test
        run: |
          cd apis/poi/tests/IntegrationTests
          dotnet restore
          dotnet build .
          dotnet test .
    
      - name: Creating issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
      
      requests:
      - name: Get single comment
        url: "https://openhacktch9q931poi.azurewebsites.net/api/healthcheck/poi"
        method: get
        expect:
          status: 'Healthy'  
          values:
            comment: This is my comment! # the JSON response `comment` field must match this value
            date_posted:
              exists: true # assertion rules can be used instead of a simple string value
            num_replies:
              gt: 0 # assert that num_replies is greater than 0